#!/usr/bin/env perl

use strict;
use warnings qw(all -syntax);
	# i like assignments in conditionals / i like to live dangerously

my $fix_mode_enabled = 0;
my %files_to_fix_set = ();

if (@ARGV and $ARGV[0] eq '--fix') {
	shift(@ARGV);
	$fix_mode_enabled = 1;
}

my $exit_error = 0;

my $alert_trailing = 1;
my $alert_indent = 1;
my $indent_char = '';
my $blank_lines = 0;

while (<>) {
	$alert_trailing and m[[\t ]\r?\n\r?$]
		and ($fix_mode_enabled or print "${ARGV}: trailing spaces, line ${.}\n")
		and ($fix_mode_enabled and $files_to_fix_set{$ARGV}=1 or $exit_error=1) and $alert_trailing=0;
	$alert_indent and m[^(\s).*\n$] and $indent_char = ($indent_char || $1) and (($indent_char ne $1) or not m[^(\s)(\1*)(\S.*)?\n$])
		and ($fix_mode_enabled or print "${ARGV}: mixed indentation, line ${.}\n")
		and ($fix_mode_enabled and print "${ARGV}: mixed indentation (not auto-fixable!), line ${.}\n" or 1)
		and $exit_error=1 and $alert_indent=0;
	m[^$] and $blank_lines+=1 or $blank_lines=0;
	m[\n$]
		or ($fix_mode_enabled or print "${ARGV}: missing final newline\n")
		and ($fix_mode_enabled and $files_to_fix_set{$ARGV}=1 or $exit_error=1);

	if (eof) {
		$alert_trailing=1 and $alert_indent=1 and $.=0 or $indent_char='';
		$blank_lines
			and ($fix_mode_enabled or print "${ARGV}: empty lines at end\n")
			and ($fix_mode_enabled and $files_to_fix_set{$ARGV}=1 or $exit_error=1);
		$blank_lines=0;
	}
}

my $line_ending_chars = '';

if ($fix_mode_enabled) {
	@ARGV = ();
	foreach my $f (keys(%files_to_fix_set)) {
		push @ARGV, $f;
	}
	$^I = '';  # enable inplace (-i) mode here and now! with no backup! exciting!
	if (@ARGV) {
		while (<>) {
			if ('' eq $line_ending_chars) {
				m<([\r\n]+)$> and $line_ending_chars = $1 or $line_ending_chars = "\n";
			}
			s/\s*?(\r?\n?\r?)$/$line_ending_chars/;
			if (m[^\r?\n?\r?$]) {
				$blank_lines+=1;
			} else {
				for(my $b=0; $b<$blank_lines; ++$b) {
					print $line_ending_chars;
				}
				$blank_lines=0;
				print;
			}
			if (eof) {
				$blank_lines=0;
				$line_ending_chars='';
			}
		}
	}
	foreach my $f (keys(%files_to_fix_set)) {
		print "$f: auto-fixed\n"
	}
}

exit 1 if $exit_error;
